//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Finder) DeepCopyInto(out *Finder) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Finder.
func (in *Finder) DeepCopy() *Finder {
	if in == nil {
		return nil
	}
	out := new(Finder)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Finder) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FinderList) DeepCopyInto(out *FinderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Finder, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FinderList.
func (in *FinderList) DeepCopy() *FinderList {
	if in == nil {
		return nil
	}
	out := new(FinderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FinderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FinderSpec) DeepCopyInto(out *FinderSpec) {
	*out = *in
	if in.Find != nil {
		in, out := &in.Find, &out.Find
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Notify = in.Notify
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FinderSpec.
func (in *FinderSpec) DeepCopy() *FinderSpec {
	if in == nil {
		return nil
	}
	out := new(FinderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FinderStatus) DeepCopyInto(out *FinderStatus) {
	*out = *in
	if in.FoundPods != nil {
		in, out := &in.FoundPods, &out.FoundPods
		*out = make(map[string]FoundSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FinderStatus.
func (in *FinderStatus) DeepCopy() *FinderStatus {
	if in == nil {
		return nil
	}
	out := new(FinderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundSpec) DeepCopyInto(out *FoundSpec) {
	*out = *in
	if in.Events != nil {
		in, out := &in.Events, &out.Events
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundSpec.
func (in *FoundSpec) DeepCopy() *FoundSpec {
	if in == nil {
		return nil
	}
	out := new(FoundSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Notify) DeepCopyInto(out *Notify) {
	*out = *in
	out.Slack = in.Slack
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Notify.
func (in *Notify) DeepCopy() *Notify {
	if in == nil {
		return nil
	}
	out := new(Notify)
	in.DeepCopyInto(out)
	return out
}
